In [2]:
import numpy as np
one_d_array=np.array([1,2,3])
print("one dimensional array is ",one_d_array)
two_d_array=np.array([[1,2,3],[3,4,5]])
print("two dimensional array is ",two_d_array)


one dimensional array is  [1 2 3]
two dimensional array is  [[1 2 3]
 [3 4 5]]


In [3]:
##To print numbers in np array
numpy_range_array=np.arange(1,100)
print("numpy array from 1 to 100 is ",numpy_range_array)

numpy array from 1 to 100 is  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [ ]:
#Different ways to create an array from the scratch 
import random 
# to create an array with zeroes
np_zeroes=np.zeros((3,3))
print("zeroes array is as follow \n",np_zeroes)

# to create an array with ones 
np_ones_array=np.ones((3,3))
print("ones array is as follow \n",np_ones_array)

# to create an array with constant number
np_constant_array=np.full((3,3),8)
print("constant array is as follow \n",np_constant_array)

# an array of random numbers
# syntax => start,stop,dimension of array either 4 X 4 like that
np_random_array=np.random.randint(0,20,(4,4))
print("random array is as follow \n",np_random_array)

# an array of sequence
# arange generates a sequnece of number that requires the start range  and the end range and u can control the sequence using the step 
np_sequence_array=np.arange(1,100,3)
print("sequence array is as follow \n",np_sequence_array)


zeroes array is as follow 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array is as follow 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
constant array is as follow 
 [[8 8 8]
 [8 8 8]
 [8 8 8]]
random array is as follow 
 [[ 9  3  3  8]
 [ 4 14 15  1]
 [ 5  9  4 12]
 [ 2  7 17 15]]
sequence array is as follow 
 [ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]
