In [1]:
import numpy as np
#Vectors is a single dimension array
np_vectors=np.array([1,2,3])
print("vector array looks like this \n",np_vectors)

# matrices is two dimensional array 
np_matrices=np.array([[1,2,3],[4,5,6]])
print("matrices looks like this \n ",np_matrices)

# tensor is n dimensional array
np_tensor=np.array([[[1,2,3],[4,5,6],
                     [7,8,9],[10,11,12]]]) 
print("tensor  looks like this \n ",np_tensor)

vector array looks like this 
 [1 2 3]
matrices looks like this 
  [[1 2 3]
 [4 5 6]]
tensor  looks like this 
  [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
