In [ ]:
import numpy as np
original_array=np.arange(1,10)
print("original array \n",original_array)

# reshape converts a single array to 3 rows , 3 columns
reshaped_array=original_array.reshape(3,3)
print("Reshaped array \n",reshaped_array)

# flatten converts the reshaped array to original array
# Returns a copy of the array, flattened into 1D.
# Changes to the result do not affect the original array
flatted_array=reshaped_array.flatten()
print("flatten array is \n",flatted_array)

#Ravel Returns a flattened view of the array if possible (not always a copy).
# Changes to the result may affect the original array (if it’s a view).
ravel=reshaped_array.ravel()
print("ravel \n",ravel)

# Transpose convert the rows=> columns and columns => row
new_array=np.array([[1,2,3],
                    [4,5,11]])
print("Transpose of array \n",new_array.T)


original array 
 [1 2 3 4 5 6 7 8 9]
Reshaped array 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
flatten array is 
 [1 2 3 4 5 6 7 8 9]
ravel 
 [1 2 3 4 5 6 7 8 9]
Transpose of array 
 [[ 1  4]
 [ 2  5]
 [ 3 11]]
