In [12]:
import numpy as np

# slicing in 1d array
np_array=np.array([1,2,3,4,5])

print("element starting from 2 to end",np_array[2:])
print("element starting from 1 to 3",np_array[1:4])

# slicing in 2d array
np_2d_array=np.array([[2,3,4],
                      [5,6,7],
                      [10,11,12]])

# Access and print the element at row 1, column 2
print("Element at row 1, column 2: \n", np_2d_array[1, 2])

# Access and print all elements from the first row
print("All elements from the first row: \n", np_2d_array[0, :])

# Access and print all elements from the second column
print("All elements from the second column:  \n", np_2d_array[:, 1])

element starting from 2 to end [3 4 5]
element starting from 1 to 3 [2 3 4]
Element at row 1, column 2: 
 7
All elements from the first row: 
 [2 3 4]
All elements from the second column:  
 [ 3  6 11]


In [22]:
# sorting in numpy array
un_sorted_array=np.array([2,3,4,1,1,0,9,8])
print("sorted array is as follow ",np.sort(un_sorted_array))

# sorting in 2d array 
unsorted_2d_array=np.array([[4,3],
                           [100,22],
                           [10,2]])
print("sorting 2d array row wise \n",np.sort(unsorted_2d_array,axis=1)) #it sorts row wise and in ascending order
print("sorting in 2d array column wise \n",np.sort(unsorted_2d_array,axis=0))

sorted array is as follow  [0 1 1 2 3 4 8 9]
sorting 2d array row wise 
 [[  3   4]
 [ 22 100]
 [  2  10]]
sorting in 2d array column wise 
 [[  4   2]
 [ 10   3]
 [100  22]]


In [ ]:
# filter method in the 1d array
np_1d_array=np.array([1,24,35,40,50,78,100,33])

# filtering the even num in the above array 
filterd_array=np_1d_array[np_1d_array %2==0]
print("filterd array of even num \n",filterd_array)


# filter method using mask 
mask=np_1d_array>60
print("filter with mask is as follow \n",np_1d_array[mask])


filterd array of even num 
 [ 24  40  50  78 100]
filter with mask is as follow 
 [ 78 100]


In [ ]:
#Indexing and where condtion
# to print the numpy array of the random number with size =10 elements
np_random = np.random.randint(1, 100,size=10)
# print(np_random)
original_np_array = np.array([19, 50, 50, 10, 9, 79, 22, 89, 50, 56])
indices=[2,5,6]
print("elements at the corresponding indices 2,5,6\n" ,original_np_array[indices])

# filtering the records using the where condtion 
# below code finds the element greater than 50 and also include the even number from that list 
where_condtion=np.where((original_np_array>50) & (original_np_array%2==0))
print("condtional array using where clause \n",original_np_array[where_condtion])

where_condtion1=np.where(original_np_array>60 ,"True","False")
# # For each element, returns "True" if the number is greater than 60, otherwise returns "False"
print("condtional array using where clause \n",where_condtion1)


elements at the corresponding indices 2,5,6
 [50 79 22]
condtional array using where clause 
 [56]
condtional array using where clause 
 ['False' 'False' 'False' 'False' 'False' 'True' 'False' 'True' 'False'
 'False']
