In [2]:
#addition of the two array
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([10,20,30])

# adding two array
# note do not perform additon like this using + symbol
addition=arr1+arr2
print("addition between array \n",addition) # [11,22,33] which is wrong

# instead of that above + always use the concatenate method to add two arrays
# concatenate is a method that accept a tuple of two arrays
addition_array=np.concatenate((arr1,arr2))
print("Addition between two array usign concatenate method \n",addition_array) # [ 1  2  3 10 20 30] this is correct method



addition between array 
 [11 22 33]
Addition between two array usign concatenate method 
 [ 1  2  3 10 20 30]


In [3]:
###NOTE: Before performing any operation such as the addition or the deletion it is mandatory  to check the compatibility between the two arrays

check_compatibility=np.size(arr1)==np.size(arr2)
print("check compatibility ",check_compatibility) #output : True because size of array 1 == size of array2

# another example
array1=np.array([1,2,3])
array2=np.array([10,20,30,40])
check_array_compatibility=np.size(array1)==np.size(array2)
print("check array compatibilty ",check_array_compatibility) #output : False size of array 1 != size of array2


check compatibility  True
check array compatibilty  False


In [4]:
# To add an array vertically and horizontally

new_original_arr=np.array([[1,2,3]
                          ,[4,5,6]])
new_row_array=np.array([7,8,9])

# Adding a new row to an array
new_row=np.vstack((new_original_arr,new_row_array))
print("Adding a new row \n",new_row)

# Adding new column to an array
new_column_array=np.array([[10],[20]])
new_column=np.hstack((new_original_arr,new_column_array))
print("After adding new column",new_column)





Adding a new row 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
After adding new column [[ 1  2  3 10]
 [ 4  5  6 20]]


In [5]:
array1=np.array([[1,2]
                ,[3,4]])
array2=np.array([[5,6]
                ,[7,8]])

# adding an array horizontally using vstack
vstack_array1=np.vstack((array1,array2))
print("adding an array horizontally using vstack \n",vstack_array1)

# adding an array vertically using hstack
hstack_array1=np.hstack((array1,array2))
print("adding an element vertically using hstack \n",hstack_array1)






adding an array horizontally using vstack 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
adding an element vertically using hstack 
 [[1 2 5 6]
 [3 4 7 8]]


In [7]:
# Deletion of an array
num_array=np.array([1,2,4,5,10])
deleted_array=np.delete(num_array,3)
print("deleted array ",deleted_array)

deleted array  [ 1  2  4 10]
