In [ ]:
import numpy as np

# Sample sales data: rows = restaurants, columns = years (2021-2025)
sales_data = np.array([
    [1,12000, 13500, 15000, 16000, 17000],  # Restaurant 1
    [2,9000,  9500,  11000, 12000, 12500],  # Restaurant 2
    [3,20000, 21000, 22000, 23000, 24000],  # Restaurant 3
    [4,15000, 15500, 16000, 16500, 17000],  # Restaurant 4
    [5,8000,  8500,  9000,  9500,  10000]   # Restaurant 5
])
print("Sales data (restaurants x years):\n", sales_data)

Sales data (restaurants x years):
 [[    1 12000 13500 15000 16000 17000]
 [    2  9000  9500 11000 12000 12500]
 [    3 20000 21000 22000 23000 24000]
 [    4 15000 15500 16000 16500 17000]
 [    5  8000  8500  9000  9500 10000]]


In [ ]:
# shape of the array
print("sales data shape \n",np.shape(sales_data))
print("========================================================================================")

# dimension of the sales data
print("dimension of the sales data \n",np.ndim(sales_data))
print("========================================================================================")

# sales of the first 3 restaurant 
print("accessing the sales of first 3 restaurant \n",sales_data[0:3])
print("========================================================================================")

# to exlude the index of the years 
# 0:3 prints the first 3 rows and 1: denotes start from column 1 instead of column 0 inorder to exclude the index
print("data after excluding index \n",sales_data[0:3, 1:])
print("========================================================================================")

# to print the total sales of the restarurant 
# note: if the axis: 0 it calculates the sales vertically
# if the axis:1 it calculates the sales horizontally
print("total sales in first three years \n ",np.sum(sales_data[0:3,1:],axis=0)) 
print("========================================================================================")

#to print the minumum sales in  sales data
print("minimum sales \n ",np.min(sales_data[0:,1:]))

# to print the maximum sales in sales data
print("maximum sales in 2 years \n",np.max(sales_data[0:3,1:]))

# to print maximum sales in complete year
print('maximum sales  \n ',np.max(sales_data[0:,1:])) 

sales data shape 
 (5, 6)
dimension of the sales data 
 2
accessing the sales of first 3 restaurant 
 [[    1 12000 13500 15000 16000 17000]
 [    2  9000  9500 11000 12000 12500]
 [    3 20000 21000 22000 23000 24000]]
data after excluding index 
 [[12000 13500 15000 16000 17000]
 [ 9000  9500 11000 12000 12500]
 [20000 21000 22000 23000 24000]]
total sales in first three years 
  [41000 44000 48000 51000 53500]
minimum sales 
  8000
maximum sales in 2 years 
 24000
maximum sales  
  24000


In [29]:
# when we need to take the axis as the 0 or the 1

# axis=0 means the operation is performed down the rows (column-wise).
    #  gives the total sales for each year (sums each column).
# axis=1 means the operation is performed across the columns (row-wise).
    #  gives the total sales for each restaurant (sums each row).

# by default the axis will be 0 so operation will be performed from the top -> bottom
# if you want to perform the operation from the left ->  right then give axis as 1

print('max sales of the restaruant 1 is ',np.max(sales_data[0:,1:],axis=1))


max sales of the restaruant 1 is  [17000 12500 24000 17000 10000]


In [33]:
# To find he average sales of each restaurant
print("avg sales ",np.mean(sales_data[0:,1:],axis=1))

avg sales  [14700. 10800. 22000. 16000.  9000.]
