In [ ]:
import numpy as np

vector1=np.array([1,2,3,4])
vector2=np.array([5,6,7,8])

# addition on the vectors
vector_addition=vector1+vector2
print("vector addition ",vector_addition)

# subtraction on the vectors
vector_subtraction=vector1-vector2
print("vector subtraction",vector_subtraction)

# dot product on the vectors
vector_dot_product=np.dot(vector1,vector2)
print("vector_dot ",vector_dot_product)

# math calculation
# (1*5)+(2*6)+(3*7)+(4*8)
# 5+12+21+32=70 outputis 70

# vectorized enabled you to apply a function to each element of the numpy array 
fruits_vector=np.array(['apple','mango','oranges','pinapple'])
vectorized_array=np.vectorize(str.upper)
print("converting the names array to upper case",vectorized_array(fruits_vector))

print("====================================================================================")
# broadcasting
# broadcasting allows you to perform the mathematical operation on any shape and size of the numpy arrays without expplicity iterating over each element using the loops 
sales_data = np.array([
    #  2020 , 2021 , 2022 , 2023 , 2024
    [1,12000, 13500, 15000, 16000, 17000],  # Restaurant 1
    [2,9000,  9500,  11000, 12000, 12500],  # Restaurant 2
    [3,20000, 21000, 22000, 23000, 24000],  # Restaurant 3
    [4,15000, 15500, 16000, 16500, 17000],  # Restaurant 4
    [5,8000,  8500,  9000,  9500,  10000]   # Restaurant 5
])

round_fun = np.vectorize(round)
output=sales_data[0:, 1:] / 12
print("Average monthly sales for each restaurant \n", output)
print()

# after rounding to 2 decimals
print("avg sales after rounding to 2 decimals ",round_fun(output,2))

vector addition  [ 6  8 10 12]
vector subtraction [-4 -4 -4 -4]
vector_dot  70
converting the names array to upper case ['APPLE' 'MANGO' 'ORANGES' 'PINAPPLE']
Average monthly sales for each restaurant 
 [[1000.         1125.         1250.         1333.33333333 1416.66666667]
 [ 750.          791.66666667  916.66666667 1000.         1041.66666667]
 [1666.66666667 1750.         1833.33333333 1916.66666667 2000.        ]
 [1250.         1291.66666667 1333.33333333 1375.         1416.66666667]
 [ 666.66666667  708.33333333  750.          791.66666667  833.33333333]]

avg sales after rounding to 2 decimals  [[1000.   1125.   1250.   1333.33 1416.67]
 [ 750.    791.67  916.67 1000.   1041.67]
 [1666.67 1750.   1833.33 1916.67 2000.  ]
 [1250.   1291.67 1333.33 1375.   1416.67]
 [ 666.67  708.33  750.    791.67  833.33]]
